-- Tremplins NA — schéma Postgres (Supabase)
-- Source de vérité versionnée. Applicable via SQL Editor, supabase CLI, ou MCP.
-- Idempotent : peut être ré-exécutée sans casser un état existant.

-- ─── Extensions ──────────────────────────────────────────────────────────────
create extension if not exists "pgcrypto"; -- gen_random_uuid()

-- ─── Helper: trigger updated_at ──────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ─── Table: sources ──────────────────────────────────────────────────────────
-- Miroir de config/sources.yaml. Le YAML reste la source de vérité (versionnée
-- dans git). seed_sources.py synchronise dans ce table pour requêtes/jointures.
create table if not exists public.sources (
  id            text primary key,
  name          text not null,
  url           text not null,
  dept          text,
  type          text not null check (type in ('network','institution','smac','venue','platform','media')),
  paths         text[] default '{}',
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

drop trigger if exists trg_sources_updated_at on public.sources;
create trigger trg_sources_updated_at
  before update on public.sources
  for each row execute function public.set_updated_at();

create index if not exists idx_sources_dept on public.sources(dept);
create index if not exists idx_sources_type on public.sources(type);

-- ─── Table: venues (base de connaissance des salles) ─────────────────────────
-- Seedée depuis sources_discovered.yaml (Wikipedia) puis enrichie au fil de
-- la découverte. Une venue peut devenir une source (via promotion manuelle).
create table if not exists public.venues (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  city          text not null,
  dept          text,
  capacity_raw  text,
  capacity_int  integer,
  url           text,
  source_id     text references public.sources(id) on delete set null, -- si promue source
  notes         text,
  origin        text not null default 'wikipedia' check (origin in ('wikipedia','manual','discovery','other')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  -- une salle est unique par (nom, ville) — case-insensitive
  unique (name, city)
);

drop trigger if exists trg_venues_updated_at on public.venues;
create trigger trg_venues_updated_at
  before update on public.venues
  for each row execute function public.set_updated_at();

create index if not exists idx_venues_dept on public.venues(dept);
create index if not exists idx_venues_source_id on public.venues(source_id);

-- ─── Table: pages (cache des pages crawlées) ─────────────────────────────────
-- Permet de détecter les mises à jour via content_hash, et de garder une
-- trace pour audit / debug du classifier.
create table if not exists public.pages (
  url           text primary key,
  source_id     text not null references public.sources(id) on delete cascade,
  content_hash  text not null,
  title         text,
  text          text,
  fetched_at    timestamptz not null default now()
);

create index if not exists idx_pages_source_id on public.pages(source_id);
create index if not exists idx_pages_fetched_at on public.pages(fetched_at);

-- ─── Table: tremplins (résultat de la détection) ─────────────────────────────
create table if not exists public.tremplins (
  id            bigint generated by default as identity primary key,
  url           text not null unique,
  source_id     text not null references public.sources(id) on delete cascade,
  dept          text,
  title         text not null,
  summary       text,
  deadline      text,                  -- "AAAA-MM-JJ" ou texte libre (LLM)
  location      text,
  confidence    real check (confidence between 0 and 1),
  content_hash  text,
  status        text not null default 'open' check (status in ('open','closed','draft')),
  first_seen    timestamptz not null default now(),
  last_seen     timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

drop trigger if exists trg_tremplins_updated_at on public.tremplins;
create trigger trg_tremplins_updated_at
  before update on public.tremplins
  for each row execute function public.set_updated_at();

create index if not exists idx_tremplins_dept on public.tremplins(dept);
create index if not exists idx_tremplins_status on public.tremplins(status);
create index if not exists idx_tremplins_last_seen on public.tremplins(last_seen desc);

-- ─── Row Level Security ──────────────────────────────────────────────────────
-- Le crawler écrit avec le service_role (bypass RLS automatique côté Supabase).
-- Le public (anon, futur frontend) peut lire les tremplins ouverts uniquement.

alter table public.sources enable row level security;
alter table public.venues enable row level security;
alter table public.pages enable row level security;
alter table public.tremplins enable row level security;

-- Policies : lecture publique sur sources actives, venues, et tremplins ouverts
drop policy if exists "public read active sources" on public.sources;
create policy "public read active sources" on public.sources
  for select using (active);

drop policy if exists "public read venues" on public.venues;
create policy "public read venues" on public.venues
  for select using (true);

drop policy if exists "public read open tremplins" on public.tremplins;
create policy "public read open tremplins" on public.tremplins
  for select using (status = 'open');

-- pages : pas de policy → pas de lecture publique (cache interne)
